# Generated by Django 5.2.4 on 2025-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="icon",
            field=models.CharField(
                blank=True, default="", help_text="Icon class or emoji", max_length=50
            ),
        ),
    ]
