# Generated by Django 5.2.4 on 2025-07-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('delivery', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('main_image', models.ImageField(upload_to='place_images/')),
                ('additional_images', models.ImageField(blank=True, null=True, upload_to='place_additional_images/')),
                ('reviews', models.ManyToManyField(blank=True, related_name='places', to='reviews.review')),
            ],
        ),
    ]
