# Generated by Django 5.2.4 on 2025-01-13 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import django.utils.timezone
from decimal import Decimal


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Unnamed Place", max_length=200)),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Unknown", "Unknown"),
                            ("Dnipro", "Дніпровський"),
                            ("Desna", "Деснянський"),
                            ("Solomyanka", "Солом'янський"),
                            ("Shevchenko", "Шевченківський"),
                            ("Pechersk", "Печерський"),
                            ("Obolon", "Оболонський"),
                            ("Podil", "Подільський"),
                            ("Svyatoshyn", "Святошинський"),
                            ("Holosiiv", "Голосіївський"),
                            ("Darnytsia", "Дарницький"),
                        ],
                        default="Unknown",
                        max_length=100,
                    ),
                ),
                ("address", models.CharField(max_length=300)),
                ("delivery", models.BooleanField(default=False)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Активний"),
                            ("Inactive", "Неактивний"),
                            ("On_moderation", "На модерації"),
                            ("Closed", "Закритий"),
                            ("Archived", "Архівний"),
                        ],
                        default="On_moderation",
                        max_length=50,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        help_text="Average rating calculated from reviews",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("main_image", models.ImageField(upload_to="place_images/")),
                (
                    "additional_images",
                    models.ImageField(
                        blank=True, null=True, upload_to="place_additional_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "opening_hours",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_places",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviews",
                    models.ManyToManyField(
                        blank=True, related_name="places", to="reviews.review"
                    ),
                ),
            ],
            options={
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaceRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="places.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Place Rating",
                "verbose_name_plural": "Place Ratings",
                "unique_together": {("user", "place")},
            },
        ),
    ]
