# Generated by Django 5.2.4 on 2025-07-25 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="reviews",
        ),
        migrations.AddField(
            model_name="place",
            name="moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_places",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="moderation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Активний"),
                    ("Inactive", "Неактивний"),
                    ("On_moderation", "На модерації"),
                    ("Approved", "Схвалено"),
                    ("Rejected", "Відхилено"),
                    ("Closed", "Закритий"),
                    ("Archived", "Архівний"),
                ],
                default="On_moderation",
                max_length=50,
            ),
        ),
    ]
