# Generated by Django 5.2.4 on 2025-07-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('shwarma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='shwarma',
            field=models.ManyToManyField(blank=True, related_name='places', to='shwarma.shwarma'),
        ),
    ]
