# Generated by Django 5.2.4 on 2025-07-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_add_custom_moderation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="reviews_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
