# Generated by Django 5.2.4 on 2025-07-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
