# Generated by Django 5.2.13 on 2026-04-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_rating_alter_placerating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='Київ', max_length=100),
        ),
    ]
