# Generated by Django 5.2.13 on 2026-04-26 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_seed_cities_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('place', 'Place'), ('review', 'Review')], max_length=16)),
                ('target_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='places_mode_target__058e00_idx'), models.Index(fields=['-created_at'], name='places_mode_created_b8da38_idx')],
            },
        ),
    ]
