# Generated by Django 5.2.4 on 2025-01-13 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        choices=[
                            (Decimal("1"), "1"),
                            (Decimal("2"), "2"),
                            (Decimal("3"), "3"),
                            (Decimal("4"), "4"),
                            (Decimal("5"), "5"),
                            (Decimal("6"), "6"),
                            (Decimal("7"), "7"),
                            (Decimal("8"), "8"),
                            (Decimal("9"), "9"),
                            (Decimal("10"), "10"),
                        ],
                        decimal_places=2,
                        max_digits=3,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_moderated", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
