# Generated by Django 5.2.4 on 2025-07-12 17:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_options_place_created_at_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_set', to='places.place'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.DecimalField(choices=[(Decimal('1'), '1'), (Decimal('2'), '2'), (Decimal('3'), '3'), (Decimal('4'), '4'), (Decimal('5'), '5'), (Decimal('6'), '6'), (Decimal('7'), '7'), (Decimal('8'), '8'), (Decimal('9'), '9'), (Decimal('10'), '10')], decimal_places=2, max_digits=3),
        ),
    ]
