# Generated by Django 5.2.4 on 2025-01-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="place",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_set",
                to="places.place",
            ),
            preserve_default=False,
        ),
    ]
