# Generated by Django 5.2.13 on 2026-04-25 07:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_add_place_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.DecimalField(choices=[(Decimal('1.0'), '1 - Very Poor'), (Decimal('2.0'), '2 - Poor'), (Decimal('3.0'), '3 - Below Average'), (Decimal('4.0'), '4 - Fair'), (Decimal('5.0'), '5 - Average'), (Decimal('6.0'), '6 - Above Average'), (Decimal('7.0'), '7 - Good'), (Decimal('8.0'), '8 - Very Good'), (Decimal('9.0'), '9 - Excellent'), (Decimal('10.0'), '10 - Outstanding')], decimal_places=2, max_digits=3),
        ),
    ]
