# Generated by Django 5.2.13 on 2026-04-25 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Front-end icon slug or emoji.",
                        max_length=64,
                    ),
                ),
                ("points_reward", models.PositiveIntegerField(default=0)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        default="bronze",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "ordering": ["tier", "title"],
            },
        ),
        migrations.CreateModel(
            name="UserPointsBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User points balance",
                "verbose_name_plural": "User points balances",
                "ordering": ["-total"],
            },
        ),
        migrations.CreateModel(
            name="PointsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Positive for awards, negative for adjustments/penalties."
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("REVIEW_CREATED", "Review created"),
                            ("REVIEW_FIRST_FOR_PLACE", "First review for place"),
                            ("REVIEW_PHOTO", "Review with dish photo"),
                            ("REVIEW_VERIFIED", "Review verified by moderator"),
                            ("REVIEW_HELPFUL_VOTE", "Review marked as helpful"),
                            ("BADGE_AWARDED", "Badge awarded"),
                            ("MANUAL_ADJUSTMENT", "Manual adjustment"),
                        ],
                        max_length=64,
                    ),
                ),
                ("ref_type", models.CharField(blank=True, default="", max_length=64)),
                ("ref_id", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Points transaction",
                "verbose_name_plural": "Points transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="gamificatio_user_id_9393e2_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="gamificatio_created_9548e8_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "reason", "ref_type", "ref_id"),
                        name="uniq_points_tx_user_reason_ref",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awarded_to",
                        to="gamification.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User badge",
                "verbose_name_plural": "User badges",
                "ordering": ["-awarded_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "badge"), name="uniq_user_badge"
                    )
                ],
            },
        ),
    ]
