"""Seed the full badge catalogue (62-badge revision).

Idempotent — ``update_or_create`` keyed on ``code``, so re-running on an
existing database updates titles/tiers in place and never duplicates.
Codes absent from this list (none today) are left untouched.
"""

from django.db import migrations

SEED_BADGES = [
    {
        'code': 'first_review',
        'title': 'First Review',
        'description': 'Posted your very first review.',
        'icon': '🥇',
        'tier': 'bronze',
        'points_reward': 0,
    },
    {
        'code': 'five_reviews',
        'title': 'Warming Up',
        'description': 'Posted five reviews.',
        'icon': '✍️',
        'tier': 'bronze',
        'points_reward': 10,
    },
    {
        'code': 'ten_reviews',
        'title': 'Ten Reviews',
        'description': "Posted ten reviews. You're a regular!",
        'icon': '📝',
        'tier': 'silver',
        'points_reward': 25,
    },
    {
        'code': 'reviews_25',
        'title': 'Storyteller',
        'description': 'Posted 25 reviews.',
        'icon': '📚',
        'tier': 'silver',
        'points_reward': 50,
    },
    {
        'code': 'reviews_50',
        'title': 'Chronicler',
        'description': 'Posted 50 reviews.',
        'icon': '🖋️',
        'tier': 'gold',
        'points_reward': 100,
    },
    {
        'code': 'reviews_100',
        'title': 'Century Club',
        'description': 'Posted 100 reviews.',
        'icon': '🏆',
        'tier': 'gold',
        'points_reward': 200,
    },
    {
        'code': 'reviews_250',
        'title': 'Living Archive',
        'description': 'Posted 250 reviews.',
        'icon': '👑',
        'tier': 'platinum',
        'points_reward': 500,
    },
    {
        'code': 'verified_first',
        'title': 'Receipt Attached',
        'description': 'Your first review verified by moderators.',
        'icon': '🧾',
        'tier': 'bronze',
        'points_reward': 10,
    },
    {
        'code': 'verified_five',
        'title': 'Verified Five',
        'description': 'Five of your reviews were verified by moderators.',
        'icon': '✅',
        'tier': 'silver',
        'points_reward': 50,
    },
    {
        'code': 'verified_15',
        'title': 'Trusted Source',
        'description': '15 verified reviews.',
        'icon': '🔏',
        'tier': 'gold',
        'points_reward': 100,
    },
    {
        'code': 'verified_50',
        'title': 'Bulletproof',
        'description': '50 verified reviews.',
        'icon': '🛡️',
        'tier': 'platinum',
        'points_reward': 250,
    },
    {
        'code': 'helpful_10',
        'title': 'Good Advice',
        'description': 'Your reviews were marked helpful 10 times.',
        'icon': '👍',
        'tier': 'bronze',
        'points_reward': 10,
    },
    {
        'code': 'helpful_fifty',
        'title': 'Helpful 50',
        'description': 'Other users marked your reviews as helpful 50 times.',
        'icon': '🤝',
        'tier': 'silver',
        'points_reward': 100,
    },
    {
        'code': 'helpful_100',
        'title': 'Crowd Favorite',
        'description': '100 helpful votes on your reviews.',
        'icon': '🙌',
        'tier': 'gold',
        'points_reward': 100,
    },
    {
        'code': 'helpful_250',
        'title': 'Voice of Reason',
        'description': '250 helpful votes on your reviews.',
        'icon': '📣',
        'tier': 'gold',
        'points_reward': 200,
    },
    {
        'code': 'helpful_500',
        'title': 'Community Pillar',
        'description': '500 helpful votes on your reviews.',
        'icon': '🏛️',
        'tier': 'platinum',
        'points_reward': 500,
    },
    {
        'code': 'voted_10',
        'title': 'Supporter',
        'description': 'Marked 10 reviews as helpful.',
        'icon': '🗳️',
        'tier': 'bronze',
        'points_reward': 5,
    },
    {
        'code': 'voted_50',
        'title': 'Cheerleader',
        'description': 'Marked 50 reviews as helpful.',
        'icon': '📢',
        'tier': 'silver',
        'points_reward': 25,
    },
    {
        'code': 'voted_100',
        'title': 'Talent Scout',
        'description': 'Marked 100 reviews as helpful.',
        'icon': '🔭',
        'tier': 'gold',
        'points_reward': 50,
    },
    {
        'code': 'first_reply',
        'title': 'Ice Breaker',
        'description': 'Wrote your first reply.',
        'icon': '💬',
        'tier': 'bronze',
        'points_reward': 5,
    },
    {
        'code': 'replies_10',
        'title': 'Chatterbox',
        'description': 'Wrote 10 replies.',
        'icon': '🗣️',
        'tier': 'bronze',
        'points_reward': 15,
    },
    {
        'code': 'replies_50',
        'title': 'Debater',
        'description': 'Wrote 50 replies.',
        'icon': '🎙️',
        'tier': 'silver',
        'points_reward': 50,
    },
    {
        'code': 'replies_100',
        'title': 'Forum Regular',
        'description': 'Wrote 100 replies.',
        'icon': '🪑',
        'tier': 'gold',
        'points_reward': 100,
    },
    {
        'code': 'sparked_10',
        'title': 'Conversation Starter',
        'description': 'Your reviews got 10 replies from others.',
        'icon': '🔥',
        'tier': 'silver',
        'points_reward': 25,
    },
    {
        'code': 'sparked_50',
        'title': 'Hot Topic',
        'description': 'Your reviews got 50 replies from others.',
        'icon': '🌋',
        'tier': 'gold',
        'points_reward': 100,
    },
    {
        'code': 'collector_5',
        'title': 'Wishlist',
        'description': 'Saved 5 places to favorites.',
        'icon': '⭐',
        'tier': 'bronze',
        'points_reward': 5,
    },
    {
        'code': 'collector_25',
        'title': 'Curator',
        'description': 'Saved 25 places to favorites.',
        'icon': '🌟',
        'tier': 'silver',
        'points_reward': 25,
    },
    {
        'code': 'fan_favorite_10',
        'title': 'Fan Favorite',
        'description': 'Places you added were favorited 10 times.',
        'icon': '💛',
        'tier': 'silver',
        'points_reward': 50,
    },
    {
        'code': 'fan_favorite_50',
        'title': 'Local Legend',
        'description': 'Places you added were favorited 50 times.',
        'icon': '💖',
        'tier': 'gold',
        'points_reward': 150,
    },
    {
        'code': 'place_scout',
        'title': 'Scout',
        'description': 'Added your first approved place.',
        'icon': '📍',
        'tier': 'bronze',
        'points_reward': 20,
    },
    {
        'code': 'place_scout_5',
        'title': 'Cartographer',
        'description': 'Added 5 approved places.',
        'icon': '🗺️',
        'tier': 'silver',
        'points_reward': 50,
    },
    {
        'code': 'place_scout_15',
        'title': 'Pathfinder',
        'description': 'Added 15 approved places.',
        'icon': '🧭',
        'tier': 'gold',
        'points_reward': 150,
    },
    {
        'code': 'place_scout_50',
        'title': 'City Mapper',
        'description': 'Added 50 approved places.',
        'icon': '🛰️',
        'tier': 'platinum',
        'points_reward': 400,
    },
    {
        'code': 'pioneer',
        'title': 'Pioneer',
        'description': 'First to review a place.',
        'icon': '🚩',
        'tier': 'bronze',
        'points_reward': 10,
    },
    {
        'code': 'pioneer_5',
        'title': 'Trailblazer',
        'description': 'First to review 5 places.',
        'icon': '⛳',
        'tier': 'silver',
        'points_reward': 50,
    },
    {
        'code': 'pioneer_25',
        'title': 'Frontier Spirit',
        'description': 'First to review 25 places.',
        'icon': '🏔️',
        'tier': 'gold',
        'points_reward': 200,
    },
    {
        'code': 'first_photo',
        'title': 'Say Cheese',
        'description': 'Attached a photo to a review.',
        'icon': '📸',
        'tier': 'bronze',
        'points_reward': 5,
    },
    {
        'code': 'photos_10',
        'title': 'Food Photographer',
        'description': '10 reviews with photos.',
        'icon': '🖼️',
        'tier': 'silver',
        'points_reward': 25,
    },
    {
        'code': 'photos_50',
        'title': 'Shava Paparazzi',
        'description': '50 reviews with photos.',
        'icon': '🎞️',
        'tier': 'gold',
        'points_reward': 100,
    },
    {
        'code': 'rater_10',
        'title': 'Sharp Eye',
        'description': 'Rated 10 places.',
        'icon': '🎯',
        'tier': 'bronze',
        'points_reward': 10,
    },
    {
        'code': 'rater_50',
        'title': 'Scorekeeper',
        'description': 'Rated 50 places.',
        'icon': '🏹',
        'tier': 'silver',
        'points_reward': 50,
    },
    {
        'code': 'explorer_10',
        'title': 'Explorer',
        'description': 'Reviewed 10 different places.',
        'icon': '🧳',
        'tier': 'silver',
        'points_reward': 25,
    },
    {
        'code': 'explorer_30',
        'title': 'Globetrotter',
        'description': 'Reviewed 30 different places.',
        'icon': '🌍',
        'tier': 'gold',
        'points_reward': 100,
    },
    {
        'code': 'districts_5',
        'title': 'District Hopper',
        'description': 'Reviewed places in 5 districts.',
        'icon': '🏙️',
        'tier': 'silver',
        'points_reward': 25,
    },
    {
        'code': 'districts_10',
        'title': 'Urban Nomad',
        'description': 'Reviewed places in 10 districts.',
        'icon': '🌆',
        'tier': 'gold',
        'points_reward': 75,
    },
    {
        'code': 'traveler_3',
        'title': 'Traveler',
        'description': 'Reviewed places in 3 cities.',
        'icon': '🚄',
        'tier': 'silver',
        'points_reward': 50,
    },
    {
        'code': 'traveler_5',
        'title': 'Jetsetter',
        'description': 'Reviewed places in 5 cities.',
        'icon': '✈️',
        'tier': 'gold',
        'points_reward': 100,
    },
    {
        'code': 'foodie',
        'title': 'Foodie',
        'description': 'Reached the Foodie level (50 points).',
        'icon': '🍽️',
        'tier': 'bronze',
        'points_reward': 0,
    },
    {
        'code': 'level_critic',
        'title': 'Critic',
        'description': 'Reached the Critic level (150 points).',
        'icon': '🎓',
        'tier': 'silver',
        'points_reward': 0,
    },
    {
        'code': 'level_expert',
        'title': 'Expert',
        'description': 'Reached the Expert level (400 points).',
        'icon': '🥋',
        'tier': 'gold',
        'points_reward': 0,
    },
    {
        'code': 'level_master',
        'title': 'Master',
        'description': 'Reached the Master level (1000 points).',
        'icon': '🏅',
        'tier': 'gold',
        'points_reward': 0,
    },
    {
        'code': 'level_legend',
        'title': 'Legend',
        'description': 'Reached the Legend level (2500 points).',
        'icon': '🐐',
        'tier': 'platinum',
        'points_reward': 0,
    },
    {
        'code': 'perfect_ten',
        'title': 'Perfect Ten',
        'description': 'Gave a place a flawless 10.',
        'icon': '💯',
        'tier': 'bronze',
        'points_reward': 5,
    },
    {
        'code': 'tough_critic',
        'title': 'Tough Critic',
        'description': 'Gave a score of 2 or lower. Ouch.',
        'icon': '🌶️',
        'tier': 'bronze',
        'points_reward': 5,
    },
    {
        'code': 'night_owl',
        'title': 'Night Owl',
        'description': 'Posted a review between midnight and 6 AM.',
        'icon': '🦉',
        'tier': 'bronze',
        'points_reward': 5,
    },
    {
        'code': 'weekend_warrior',
        'title': 'Weekend Warrior',
        'description': 'Posted 5 reviews on weekends.',
        'icon': '🍻',
        'tier': 'bronze',
        'points_reward': 10,
    },
    {
        'code': 'long_read',
        'title': 'Long Read',
        'description': 'Wrote a review of 500+ characters.',
        'icon': '📖',
        'tier': 'bronze',
        'points_reward': 10,
    },
    {
        'code': 'active_7',
        'title': 'Regular Guest',
        'description': 'Posted reviews on 7 different days.',
        'icon': '📅',
        'tier': 'silver',
        'points_reward': 25,
    },
    {
        'code': 'active_30',
        'title': 'Part of the Furniture',
        'description': 'Posted reviews on 30 different days.',
        'icon': '🗓️',
        'tier': 'gold',
        'points_reward': 150,
    },
    {
        'code': 'veteran_year',
        'title': 'One Year With Us',
        'description': 'A member for a full year.',
        'icon': '🎂',
        'tier': 'silver',
        'points_reward': 50,
    },
    {
        'code': 'badge_collector_10',
        'title': 'Badge Collector',
        'description': 'Earned 10 badges.',
        'icon': '🎖️',
        'tier': 'silver',
        'points_reward': 25,
    },
    {
        'code': 'badge_collector_25',
        'title': 'Trophy Room',
        'description': 'Earned 25 badges.',
        'icon': '🏵️',
        'tier': 'gold',
        'points_reward': 100,
    },
]


def seed_badges(apps, schema_editor):
    Badge = apps.get_model("gamification", "Badge")
    for entry in SEED_BADGES:
        Badge.objects.update_or_create(code=entry["code"], defaults=entry)


def unseed_badges(apps, schema_editor):
    # Keep user-earned rows intact on rollback; only drop badges that
    # were never awarded.
    Badge = apps.get_model("gamification", "Badge")
    Badge.objects.filter(
        code__in=[b["code"] for b in SEED_BADGES], awarded_to__isnull=True
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("gamification", "0003_badge_tier_platinum_new_reasons"),
    ]

    operations = [
        migrations.RunPython(seed_badges, unseed_badges),
    ]
