# Generated by Django 5.2.4 on 2025-01-13 12:30

from django.db import migrations
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_groups"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
