# Generated by Django 5.2.4 on 2025-07-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_custom_manager"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
