# Generated by Django 5.2.15 on 2026-07-04 17:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_moderationlog'),
        ('users', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, help_text="User's preferred/home city — used to personalize defaults.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='places.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–15 digits, optional leading +).', regex='^\\+?[1-9]\\d{6,14}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the user accepted the Terms of Service, set once at registration.', null=True),
        ),
    ]
